#!/bin/bash

restartNginx () {
  systemctl start nginx
}

checkNginx () {
    NginxThreadAfter=`ps -A|grep nginx|wc -l`
if [ $NginxThreadAfter -ne 0 ]; then
              echo "-- Nginx is running!"
break
fi
}

notrunning () {
  echo "Error:"
  echo "-- Nginx is not running!"
  echo "-- Trying to restart Nginx at $(date +"%d.%m.%y %H:%M:%S")..."
}
########################################################################

nginx -t > /dev/null 2>&1

if [ $? -eq 0 ]; then
   echo "Make backup of nginx website configuration"
   mkdir -p /root/backup_nginx_config/
   cp -a /etc/nginx/* /root/backup_nginx_config/
else
   echo "Wrong Nginx configuration!"
fi

NginxThread=`ps -A|grep nginx|wc -l`
counter=0
while [ $NginxThread -eq 0 ]
do
  notrunning
  restartNginx
  checkNginx
  counter=$((counter+1))
  if [[ "$counter" -eq 2 ]]; then
    sleep 60
  elif [[ "$counter" -eq 3 ]]; then
    echo "-- Trying to restore Nginx from backup $(date +"%d.%m.%y %H:%M:%S")..."
    cp -a /root/backup_nginx_config/* /etc/nginx/
    notrunning
    restartNginx
    checkNginx
    break
  fi
  echo "-- Nginx is running!"
done

grep nginx_monitoring /etc/crontab > /dev/null 2>&1
if [ $? -eq 0 ]; then
   echo "There is nothing to do anymore! Good bye!"
else echo "Adding this script to cronjobs..."
   echo "*/5 * * * * root /bin/bash -c /root/nginx_monitoring >> /dev/null 2>&1" >> /etc/crontab
fi

echo "-- Nginx is running!"
