#!/bin/bash

restartNginx () {
  systemctl start nginx
}

nginx -t
if [ $? -eq 0 ]; then
   echo "Make backup of nginx website configuration"
   mkdir -p /root/backup_nginx_config/
   cp -a /etc/nginx/* /root/backup_nginx_config/
else
   echo "Wrong Nginx configuration!"
fi

echo "Checking Nginx status..."

NginxThread=`ps -A|grep nginx|wc -l`

if [ $NginxThread -eq 0 ]; then
      echo "Error:"
      echo "-- Web-server Nginx is not running!"
      echo "-- Trying to restart Nginx at $(date +"%d.%m.%y %H:%M:%S")..."
      restartNginx
      sleep 5

           echo "Current status:"
           NginxThreadAfter=`ps -A|grep nginx|wc -l`
           if [ $NginxThreadAfter -eq 0 ]; then
              echo "-- Nginx is still not running!"
              echo "-- Trying to restart Nginx second time at $(date +"%d.%m.%y %H:%M:%S")..."
              restartNginx
              sleep 60

                   echo "Current status:"
                   NginxThreadAfter=`ps -A|grep nginx|wc -l`
                   if [ $NginxThreadAfter -eq 0 ]; then
                      echo "-- Nginx is still not running!"
                      echo "-- Trying to restart Nginx third time at $(date +"%d.%m.%y %H:%M:%S")..."
                      restartNginx
                      sleep 60

                        echo "Current status:"
                        NginxThreadAfter=`ps -A|grep nginx|wc -l`
                        if [ $NginxThreadAfter -eq 0 ]; then
                           echo "-- Nginx is still not running!"
                           echo "-- Trying to restore Nginx from backup $(date +"%d.%m.%y %H:%M:%S")..."
                           cp -a /root/backup_nginx_config/* /etc/nginx/
                           echo "-- Trying to restart Nginx after restoration at $(date +"%d.%m.%y %H:%M:%S")..."

                           restartNginx
                           sleep 10
                                   echo "Current status:"
                                NginxThreadAfter=`ps -A|grep nginx|wc -l`
                                if [ $NginxThreadAfter -eq 0 ]; then
                                   echo "-- Nginx is still not running!"
                                else
                                   echo "-- Nginx is running..."
                                fi

                        else
                           echo "-- Nginx is running..."
                        fi

                   else
                      echo "-- Nginx is running..."
                   fi

           else
              echo "-- Nginx is running..."
           fi
else
   echo "--Nginx is running..."
fi

grep nginx_monitoring /etc/crontab
if [ $? -eq 0 ]; then
   echo "There is nothing to do anymore! Good bye!"
else echo "Adding this script to cronjobs..."
   echo "*/5 * * * * root /bin/bash -c /root/nginx_monitoring >> /dev/null 2>&1" >> /etc/crontab
fi
