#!/bin/bash
###############

echo ""
echo "Welcome to the password generator."
echo ""

echo -n "Enter number of characters: "
read NUMBER_OF_CHARACTERS
echo ""

echo -n "Do you want to use special characters? [yes/no]:"
read SPECIAL_CHARACTERS

mkpasswd() {
  cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w $NUMBER_OF_CHARACTERS | head -n 1 | xargs echo;
}

mkpasswdspecchar () {
   cat /dev/urandom | tr -dc "a-zA-Z0-9!@#$%^&*()_+?><~\`;" | fold -w $NUMBER_OF_CHARACTERS | head -n 1 | xargs echo;
}

if [ $SPECIAL_CHARACTERS == "yes" ] ; then
        mkpasswdspecchar
else
        mkpasswd
fi

