---
# install nginx, php-fpm and awslogs
- name: Install default nginx, php-fpm and awslogs
  hosts: all
  become: yes

  vars:
    source_file: ./files/awslogs.conf
    destin_file: /etc/awslogs

  tasks:
  - name: Enable nginx and php for amazon linux 2
    shell: "amazon-linux-extras enable nginx1.12 php7.2 epel"
    become: yes

# install nginx
  - name: Install nginx
    yum:
      name: nginx
      update_cache: yes
      state: latest

  - name: start nginx and enable it
    service:
      name: nginx
      state: started
      enabled: yes

# install php-fpm
  - name: Install php-fpm
    yum:
      name:
        - php-fpm
        - php-mbstring
        - php-xml
        - php-cli
        - php-json
        - php-mysqlnd
        - php-pdo
        - php-common
      state: latest

  - name: start php-fpm and enable it
    service:
      name: php-fpm
      state: started
      enabled: yes


# install awslogs
  - name: Install CloudWatch Log Agent
    yum:
       name: awslogs
       state: present

  - name: Start awslogs service
    service:
      name: awslogsd
      state: started
      enabled: yes

  - name: Configure AWS CloudWatch Logs Agent
    ansible.builtin.shell: region=$(curl 169.254.169.254/latest/meta-data/placement/availability-zone | sed s'/.$//') && sudo sed -i -e "s/region = us-east-1/region = $region/g" /etc/awslogs/awscli.conf
    become: true

  - name: Configure awslogs.conf
    copy:
      src: "{{ source_file }}"
      dest: "{{ destin_file }}"
      mode: 644
    notify:
      - Restart awslogs


  handlers:
  - name: Restart awslogs
    service:
      name: awslogsd
      state: restarted


# install mariadb and phpmysql

- name: Install mysql and phpmyadmin
  hosts: phpmyadmin
  become: yes

  tasks:
  - name: Install mariadb
    yum:
      name:
        - mariadb
        - mariadb-server
      state: latest

  - name: start mariadb
    service:
      name: mariadb
      enabled: true
      state: started

  - name: Creates phpmyadmin directory
    file:
      path: /usr/share/nginx/html/phpmyadmin/
      state: directory

  - name: Setup phpMyAdmin
    ansible.builtin.unarchive:
      src: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
      dest: /usr/share/nginx/html/phpmyadmin
      extra_opts: [--strip-components=1]
      remote_src: yes
    notify:
      - Restart nginx
      - Restart php-fpm
      - Restart mariadb


  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
  - name: Restart php-fpm
    service:
      name: php-fpm
      state: restarted
  - name: Restart mariadb
    service:
      name: mariadb
      state: restarted
